### ISSUE TITLE
[Bug] Typeorm needs consistent entry point

### ISSUE THREAD

**Issue by Afulton11** [Afulton11/writzsol#20]
The typeorm package expects a consistent entry-point when being used. Currently, we assume`/api/gql` will be called before any other url. 

If the expected url is called first, everything works as expected.

However, if we call any other endpoint first, we end up with a `ConnectionNotFoundError`. Here's error output from a vercel deployment: 
```js
ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/var/task/node_modules/typeorm/error/ConnectionNotFoundError.js:10:28)
    at ConnectionManager.get (/var/task/node_modules/typeorm/connection/ConnectionManager.js:38:19)
    at getRepository (/var/task/node_modules/typeorm/index.js:269:35)
    at new WritzsolTypeORMAdapterInstance (/var/task/.next/serverless/pages/api/auth/[...nextauth].js:733:77)
    at WritzsolTypeORMAdapter.getAdapter (/var/task/.next/serverless/pages/api/auth/[...nextauth].js:744:12)
```

This is because `createConnection` has yet to be called; the endpoint hasn't been called by anyone. 

The app will still function once that endpoint is run, but until then nothing will work properly.

To fix this, I suggest looking at this example on github with typeorm & next.js: https://github.com/mthomps4/next-now-test/tree/next-typeorm-example

They have an 'initializers' folder that is used to initialize the database. Then, in every single place they use it, they import the file `initializers/database`.

A Quick fix is to do something similar and place the import at the top of every single Next.js page and api endpoint.

**Comment by Afulton11** [comment]
The import would only be necessary in API endpoints that use a typeorm entity.
